name: "Fraser Lab @ UCSF"
description: "This is the official web page for the James Fraser Lab at UCSF."

url: "http://fraserlab.com"

paginate: 5
paginate_path: "news/page:num"

permalink: pretty
highlighter: pygments
markdown: rdiscount
