name: "Pathogen Genomics and Evolution Group"
description: "This is the official web page for the Pathogen Genomics and Evolution Group in the Department of Veterinary Medicine at the University of Cambridge."

url: "https://pathgenevocam.github.io"

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/

collections:
        affiliates:
                output: true
        members:
                output: true
        publications:
                output: true
        reviews:
                output: true
        alumni:
                output: true
        sep:
                output: true
        visitors:
                output: true
        undergrads:
                output: true
        pets:
                output: true
